# Generated by Django 4.2.3 on 2023-10-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
