# Generated by Django 4.2.3 on 2023-10-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_avis_commentaire_alter_produit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
