// import React from "react";

const cars = [
  {
    directory: "../assets/images/products/product1.png",
    name: "Tesla Model 3",
    brand: "Tesla",
    model: "Model 3",
    transmission: "Electric",
    engine_type: "Electric",
    engine_name: "Tesla electric motor",
    performance: {
      "0_to_60_mph": 5.8,
      top_speed: 225,
    },
    style: "Sport sedan",
    price: 46990,
    price_cfa: 29844250,
  },
  {
    name: "Porsche Taycan",
    brand: "Porsche",
    model: "Taycan",
    transmission: "Electric",
    engine_type: "Electric",
    engine_name: "Porsche electric motor",
    performance: {
      "0_to_60_mph": 3.5,
      top_speed: 260,
    },
    style: "Sport coupe",
    price: 79900,
    price_cfa: 50675625,
  },
  {
    name: "Audi e-tron GT",
    brand: "Audi",
    model: "e-tron GT",
    transmission: "Electric",
    engine_type: "Electric",
    engine_name: "Audi electric motor",
    performance: {
      "0_to_60_mph": 3.3,
      top_speed: 245,
    },
    style: "Sport coupe",
    price: 104900,
    price_cfa: 65740000,
  },
  {
    name: "BMW i4",
    brand: "BMW",
    model: "i4",
    transmission: "Electric",
    engine_type: "Electric",
    engine_name: "BMW electric motor",
    performance: {
      "0_to_60_mph": 5.7,
      top_speed: 240,
    },
    style: "Sport sedan",
    price: 55900,
    price_cfa: 35447500,
  },
  {
    name: "Mercedes-Benz EQS",
    brand: "Mercedes-Benz",
    model: "EQS",
    transmission: "Electric",
    engine_type: "Electric",
    engine_name: "Mercedes-Benz electric motor",
    performance: {
      "0_to_60_mph": 4.3,
      top_speed: 220,
    },
    style: "Luxury sedan",
    price: 102350,
    price_cfa: 64920625,
  },
  {
    name: "Tesla Model S",
    brand: "Tesla",
    model: "Model S",
    transmission: "Electric",
    engine_type: "Electric",
    engine_name: "Tesla electric motor",
    performance: {
      "0_to_60_mph": 2.1,
      top_speed: 261,
    },
    style: "Sport sedan",
    price: 94990,
    price_cfa: 59994000,
  },
  {
    name: "Porsche 911",
    brand: "Porsche",
    model: "911",
    transmission: "Manual",
    engine_type: "Gas",
    engine_name: "Porsche flat-six engine",
    performance: {
      "0_to_60_mph": 3.7,
      top_speed: 261,
    },
    price: 94990,
    price_cfa: 59994000,
  },
];
export default cars;
